# Generated by Django 4.0.6 on 2022-07-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.BooleanField(choices=[(True, 'Online'), (False, 'Offline')], default=False),
        ),
    ]
