# Generated by Django 4.0.6 on 2022-08-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.TextField(),
        ),
    ]
