# Generated by Django 4.0.6 on 2022-08-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_question_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='published',
            field=models.BooleanField(choices=[(True, 'published'), (False, 'Not published')], default=False),
        ),
    ]
