# Generated by Django 4.0.6 on 2022-08-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_question_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default='static/tests/category/images/default.png', upload_to='static/tests/category/images/'),
        ),
    ]
