# Generated by Django 4.1 on 2022-11-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0006_alter_category_cat_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="published",
            field=models.BooleanField(
                choices=[(True, "Published"), (False, "Not published")], default=False
            ),
        ),
    ]
