# Generated by Django 4.1 on 2022-11-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0007_alter_question_published"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="cat_desc",
            new_name="desc",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="cat_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="cat_name",
            new_name="name",
        ),
    ]
