# Generated by Django 4.1 on 2022-11-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0008_rename_cat_desc_category_desc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="desc",
            new_name="description",
        ),
    ]
